### ISSUE TITLE
How to set vmax and vmin of cmap in ClusterMapPlotter()

### ISSUE THREAD

**Issue by XuejianXiong** [DingWB/PyComplexHeatmap#75]
Good morning,

I would like to set a same range, i.e. vmin and vmax, of cmap in the heatmap for several figures using the function ClusterMapPlotter(). My code is as follows:

heatmap = pch.ClusterMapPlotter(
                data=heatmap_data.T,
                top_annotation=col_ha,
                col_cluster=False,
                row_cluster=True,
                label="values",
                col_dendrogram=False,
                row_dendrogram=True,
                show_rownames=True,
                show_colnames=False,
                legend_gap=7,
                vmin=0,
                vmax=30,
                cmap="parula", 
                rasterized=True,
                tree_kws={"row_cmap": "Dark2"},
                ylabel=f"Protein (10 in total)",
                xlabel=f"Run (100 in total)",
                legend_hpad=7,
                yticklabels=True,
                xticklabels_kws={"labelrotation": -45, "labelcolor": "blue"},
                yticklabels_kws={"labelsize": 8},
        )        

However, the legend in the output figure did not show the range from 0 to 30, but the real minimum and maximum in the heatmap_data. 

I would like to know how to solve this problem. Thank you!

**Comment by DingWB** [comment]
Were you using the latest version of PyComplexHeatmap? If not, please upgrade to the latest version. @XuejianXiong

**Comment by XuejianXiong** [comment]
Thank you @DingWB. I upgraded to the version 1.7.3, but still have the same problem.

**Comment by DingWB** [comment]
This is weird; this bug was fixed a long time ago.
Please print `heatmap.vmin, heatmap.vmax, heatmap.legend_kws` after running `heatmap = pch.ClusterMapPlotter(**)`.

**Comment by XuejianXiong** [comment]
The output looks good "30 0 {'vmin': 0, 'vmax': 30}". However in the figures (attached), it still shows different values in the legend for different heatmaps.
<img width="1064" alt="Screenshot 2024-05-15 at 5 30 12 PM" src="https://github.com/DingWB/PyComplexHeatmap/assets/25825441/9ae81b5e-41cc-4989-8566-a0d70fb4be89">

**Comment by DingWB** [comment]
Please install the latest version from github, and follow [this example](https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/advanced_usage.html#Add-selected-rows-labels) to see whether the legend has the same vmax and vmin as provided in the code (vmin=-2.2,vmax=2.3,).

If it is still not working, then you need to paste your data and code here.

**Comment by DingWB** [comment]
Hi @XuejianXiong ,

How is it going? Did it work?

**Comment by XuejianXiong** [comment]
Hi @DingWB,

It worked! It seems my virtual environment caused issues with the package upgrading. I have to manually delete the old version and reinstall using pip. 
Thank you for help!

Best,
Xuenjian
